version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/worship
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  worker:
    build: ./worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB:
